name: Handle issues
on:
    issues:
        types: [opened, edited]
jobs:
    comment:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: Comment Hello World!!
              if: github.event.action == 'opened'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh issue comment ${{ github.event.issue.number }} --repo ${{ github.repository }} --body "Hello World!!"
            - name: Comment Change The World!!
              if: github.event.action == 'edited'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh issue comment ${{ github.event.issue.number }} --repo ${{ github.repository }} --body "Change The World!!"
